name: CD - Python

on:
  pull_request:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Criar pacote do projeto
        run: |
          zip -r controle-projetos-python.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x ".idea/*" \
            -x ".venv/*"

      - name: Publicar pacote
        uses: actions/upload-artifact@v4
        with:
          name: controle-projetos-python
          path: controle-projetos-python.zip