name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}